### ISSUE TITLE
gitignore the godot-git-plugin?

### ISSUE THREAD

**Issue by boukew99** [godotengine/godot-git-plugin#113]
- Is the plugin supposed to be ignored by .gitignore? Seems like something mainly for local use, especially when collaborating with different OS's.
- Then what are the standard `.gitignore` and `.gitatributes` files actually?
- Also, should you only install the folder of your specific OS when installing from the Asset Library?

The documentation (v1 & v2) does not provide theses answers.
Or it could be me misunderstanding, because I see it is more as an "global" editor plugin.

Though nice plugin! Helps me out while learning command line.

**Comment by ChronicallySerious** [comment]
> Is the plugin supposed to be ignored by .gitignore? Seems like something mainly for local use, especially when collaborating with different OS's.

Whether or not you want the plugin to be checked into your repository depends on how easy you want your project to be setup-able for other people on your team. If you want your artist coworker to not bother about setting up the Git CLI or anything else apart from just your project, then you shouldn't ignore the plugin because the main audience of this plugin is people who are not comfortable with the Git CLI but can use the UI with no issues.

However, if you decide to keep it out, they can also just download the plugin if they really need it anyway. People who are extremely comfortable with the Git CLI will likely find the plugin limiting because we only add features that developers will use reasonably regularly. If you are a solo developer, you probably don't want to check the plugin into Git since you are not going to collaborate with other people as often.

> what are the standard .gitignore and .gitatributes files actually?

Apart from the decision to add this plugin to your repository, you can reference this section of the documentation about [files to exclude from your VCS](https://docs.godotengine.org/en/stable/tutorials/best_practices/version_control_systems.html)

The .gitignore and .gitattributes file that this plugin outputs (as of v2.0) are picked up from [here](https://github.com/github/gitignore/blob/main/Godot.gitignore)

There is also an upcoming feature in Godot 4.0 which will create the .gitignore and .gitattributes file for you - https://github.com/godotengine/godot/pull/42447

> should you only install the folder of your specific OS when installing from the Asset Library?

If you don't care about the other OSes then you can safely ignore them, however, this again depends on your specific use case as I mentioned at the top. If you have teammates who would want to use the plugin on other OSs then you would want to let the other binaries be where they are.

> The documentation (v1 & v2) does not provide theses answers.

Would you like such information to be put on the Wiki? We can do that if that seems reasonable.

**Comment by boukew99** [comment]
My use case is indeed solo dev, but also repos with godot addons.

> Whether or not you want the plugin to be checked into your repository depends on how easy you want your project to be setup-able for other people on your team

Installing the plugin is pretty easy via Assetlib. And Windows and MacOs users need to do an extra step at installation anyway, which is arguably harder / more unfamiliar than installing the plugin using the in-editor AssetLib. So not sure how usefull it is, if I understand it right. Though mentioning you can gitignore the plugin is a nice tip for my use case.

>The .gitignore and .gitattributes file that this plugin outputs (as of v2.0) are picked up from [here](https://github.com/github/gitignore/blob/main/Godot.gitignore)

You could just add this ^ or "(specifications)" with a link.

>If you don't care about the other OSes then you can safely ignore them, however, this again depends on your specific use case as I mentioned at the top. If you have teammates who would want to use the plugin on other OSs then you would want to let the other binaries be where they are.

You could mention this shortly or something like: "this plugin contains git for Linux, MacOs and Windows".

**Comment by ChronicallySerious** [comment]
Cool, I have added this info in the Wiki and the releases from now on will mention that the ZIP has binaries for all 3 platforms
