### ISSUE TITLE
New build with Godot 4.0 support?

### ISSUE THREAD

**Issue by ianling** [godotengine/godot-git-plugin#140]
Since https://github.com/godotengine/godot-git-plugin/pull/132 was merged, could someone please generate a new release? Thank you!

**Comment by twaritwaikar** [comment]
Unfortunately that PR required us to make some changes in Godot, which means we are locked before making new releases until the next Godot beta release, since those builds will be only usable by people who build Godot themselves from a recent commit on it's master branch. 

Question: Would it still be beneficial for you if we released binaries that can be used directly but would require users to use a latest Godot build, at least till the next Godot 4 beta comes out?

**Comment by ianling** [comment]
@twaritwaikar understood, thanks for the response! I will just wait for the next beta release.
