### ISSUE TITLE
Git Plugin not working with Godot 4 Beta14

### ISSUE THREAD

**Issue by columbiacolles** [godotengine/godot-git-plugin#157]
![gitplugin_godot4beta14](https://user-images.githubusercontent.com/122221262/214384635-f3103778-cbee-4163-800b-5438a71fca00.png)

**Comment by twaritwaikar** [comment]
@columbiacolles I take your issue got resolved later on? Do you know what fixed it?

**Comment by columbiacolles** [comment]
Sorry, should have made a note. The issue is already described in [#155 ](url).

**Comment by Frontrider** [comment]
I have the same message, the entry point script is named "godot-git-plugin.gd" in the plugin.cfg file but this script is missing from the download I have from the asset store.

**Comment by el-falso** [comment]
Activating the plugin via the Plugin tab doesn't work in general because GDExtensions are loaded automatically when you open the project.

It's even written in the installation docs:
> Note: you do NOT need to manually enable the plugin in the Project > Project Settings > Plugins tab. In fact, you can't; that tab is for script-based plugins, GDExtension plugins, like this one, will be loaded automatically.

A solution which would work is that we hide GDExtensions from the Plugin tab that users don't try to activate them and have a separate tab with installed GDExtensions.

**Comment by Frontrider** [comment]
> A solution which would work is that we hide GDExtensions from the Plugin tab that users don't try to activate them and have a separate tab with installed GDExtensions.

Yap, this would be a great solution.
