### ISSUE TITLE
Plans to document this?

### ISSUE THREAD

**Issue by locness3** [godotengine/godot-git-plugin#16]
Are there any plans to add some documentation to the official docs?

**Comment by IronicallySerious** [comment]
The VCS API that was added to Godot 3.2 to enable this plugin is documented here: https://docs.godotengine.org/en/3.2/classes/class_editorvcsinterface.html

However, the plugin usage is documented almost completely in the report [here](https://godotengine.org/article/gsoc-2019-progress-report-3#vcs-integration).

Rest assured, I personally feel that this plugin is quite small in its extent because of the nature in which this has been implemented. This is the implementation of the API specified by Godot. It merely implements the API that has been declared by Godot's EditorVCSInterface. Most of the documentation worthy stuff is in the engine.

If still there is a need for documentation, I can also do that if the need arises.

**Comment by follower** [comment]
FWIW I think there would be a big benefit from having this plugin documented in the official docs--as IMO that's where people are most likely to go looking for the information.

My guess would be that adding a [tutorial](https://github.com/godotengine/godot-docs/tree/master/tutorials) would probably be a good place for such documentation.

Essentially, just copying the content of the [existing documentation](https://godotengine.org/article/gsoc-2019-progress-report-3#vcs-integration) would be a great start--because most people won't find the documentation in its current location.

To me, the VCS API documentation is appropriate for people wanting to implement a VCS plugin but it's not suitable for people wanting to use a/this specific plugin.

Also, I may be misunderstanding your comment @IronicallySerious, but I feel that you're massively under-rating the significance of your work on this plugin--there's a lot of people who were looking forward to a git VCS plugin specifically who use it as a core part of their development work flow. And having an in-editor GUI based approach to VCS has the potential to make the functionality available to people for whom CLI tools are less accessible.

While you've built the git plugin on top of a lot of other work, it's really the key piece of the puzzle that actually makes all that other work actually functional for people on a day-to-day basis. 

Existing doc bug in doc repo: https://github.com/godotengine/godot-docs/issues/2838

**Comment by locness3** [comment]
@IronicallySerious I agree with @follower. Most people won't go to the blog post. And the EditorVCSInterface docs won't help users who just want to **use*** VCS since there's no mention of a git plugin on that page.

**Comment by IronicallySerious** [comment]
Alright, then this is clearly a valid request. Adding documentation is this way is much required.

**Comment by IronicallySerious** [comment]
How does this look? https://github.com/godotengine/godot-git-plugin/wiki

**Comment by IronicallySerious** [comment]
I figured making a Wiki would be a starting point. The official docs can point here so that there are fewer inconsistencies

**Comment by locness3** [comment]
maybe talk about OS compatibility?

**Comment by IronicallySerious** [comment]
Okay, I will add it in. Maybe wording it differently will help infer that the plugin doesn't contain OS-specific code.

**Comment by IronicallySerious** [comment]
Usage documentation is now at https://github.com/godotengine/godot-git-plugin/wiki
To put a link in the official docs, I think a better place to open an issue is at godot-docs. Since this is not related to this plugin, I will close this issue for now.

**Comment by follower** [comment]
Thanks for your work on this.

A couple of thoughts after taking a quick look:

1. I can see some logic in keeping the documentation in the wiki for now with a link from the official docs.

2. I suspect it's not important to most people who will want to use the plugin that this is "an implementation of the EditorVCSInterface API". I would be inclined to summarise as something more like:

    > This plugin lets you use the Git version control system inside the Godot editor.

3. I would be inclined to split installation step 1 into 2 or 3 steps--I suspect people are liable to skip later sentences in longer paragraphs and so miss the importance of the last sentence.

   Maybe something like (with the existing links):

   > .1. Download the latest release from the Git addon GDNative plugin repository.
   > .2. Extract the contents in the root of your Godot project folder.
   >     (Make sure the bin/ folder is in the root directory of your project.)
   > [...]

   Or:

   > [...]
   > 2. Extract the contents in the root of your Godot project folder.
   > 3. Make sure the bin/ folder is in the root directory of your project, like this:
   >     [screen shot and/or text representation of project directory tree & content]
   > [...]

Will add a note about the current plans to the existing godot-docs issue.

Thanks!

**Comment by IronicallySerious** [comment]
Made some more changes as you requested. Added a small features section too.
