### ISSUE TITLE
Error when installing plugin with Godot 4.0 Stable on Windows 11

### ISSUE THREAD

**Issue by mahmoudhossam** [godotengine/godot-git-plugin#168]
I'm getting this error when trying to use this plugin with Godot 4.0:

```
Unable to load addon script from path: 'res://addons/godot-git-plugin/godot-git-plugin.gd'. This might be due to a code error in that script.
Disabling the addon at 'res://addons/godot-git-plugin/plugin.cfg' to prevent further errors.
```

I don't see this file anywhere in the repo, maybe Godot changed the format for plugins?

**Comment by otterscript** [comment]
This is due to enabling the plugin in the plugins tab of project settings. Once you add the plugin to the project files, the editor will automatically use it. Just go to the project tab, then version control settings to set it up. Here's the wiki with more info on that: https://github.com/godotengine/godot-git-plugin/wiki/Git-plugin-v3

**Comment by mahmoudhossam** [comment]
Yeah, the version control settings don't change after I've installed the plugin.

They still look like this:
![image](https://user-images.githubusercontent.com/619795/223386808-926ea6cf-162d-4e38-8d3a-2808ead701a7.png)

**Comment by mahmoudhossam** [comment]
Ah, I realized I was looking at the wrong place, closing...
