### ISSUE TITLE
Why ignore bin, lib and .lib folders by default?

### ISSUE THREAD

**Issue by gamedevsam** [godotengine/godot-git-plugin#17]
I think it makes sense to check in this plugin into source control to minimize setup pain for team members. I renamed the bin folder .lib so it doesn't show up in godot's FileSystem viewer (I want to keep that as clean as possible), and it was ignored by default.

I had to change my gitignore to this:

```
# Import cache
.import

# Exported Binaries
.export

# Don't ignore .lib folder
!.lib
```

Even then the plugin didn't pick up on .lib directory, I had to use a git gui to check that in.

**Comment by Calinou** [comment]
Committing generated files into a Git repository is generally considered bad practice, especially due to Git's distributed nature. When you clone a Git repository, you get its whole history by default (which is why cloning can be slow).

Committing a script that downloads the required binaries is likely a better idea. We could provide such scripts as an example.

**Comment by IronicallySerious** [comment]
Users still have the freedom to edit the .gitignore as they like. Setting up the plugin is IMO not as complex too. Adding the clause to not ignore the `.lib` folder could bring up quite a lot of Git related problems, like bloated commits, large repo size etc.

**Comment by IronicallySerious** [comment]
.gitignore is still completely customizable by the users. If someone needs a special clause in any of the git config files then they are free to do so, the plugin does not stop them.

However, I do feel the current .gitignore is going to be the barebones .gitignore that is common to every Godot project. Hence, I will be closing this for now.
