### ISSUE TITLE
Can't commit Chinese files.

### ISSUE THREAD

**Issue by Az-qianchen** [godotengine/godot-git-plugin#182]
The Chinese characters cannot be displayed correctly in the Commit panel, and files with Chinese names cannot be committed, but can be pulled. 

![tmpA13C](https://user-images.githubusercontent.com/52212525/235047572-594bff8b-8703-4eae-be04-1595c2879146.png)

Additionally, I am unable to use SSH to connect to my remote repository in Godot, as it becomes unresponsive, but I am able to use HTTPS to connect to my remote repository.

Win 11 and Mac
Godot 4.0.2
Godot Git Plugin V3.0.0

**Comment by markeel** [comment]
I believe the problem with chinese characters are related to the lack of UTF-8 support on the libgit2 interface that is addressed in #190.  The inability to SSH is also likely the fact that if you have a user id, it assumes you have are using a password even if SSH credentials are specified.  That change is fixed in #173.
