### ISSUE TITLE
error loading extension --> gitplugin.gdextension

### ISSUE THREAD

**Issue by RakibRyan** [godotengine/godot-git-plugin#206]

**Comment by InfGame** [comment]
getting the same error. can't even open the faulty file

**Comment by DanielJorn** [comment]
Godot 4.1.1
MacOs Ventura 13.5
Git plugin v3

[As of July 2023, the Git plugin hasn't been updated to work with Godot 4.1 and later yet.
](https://docs.godotengine.org/en/stable/tutorials/best_practices/version_control_systems.html)

is there a way to add git plugin for 4.1?

**Comment by Arakade** [comment]
Seeing the same problem.  Tried to work around.

Added to the file `"<project dir>\addons\godot-git-plugin\git_plugin.gdextension"`:
```ini
compatibility_minimum = 4.0
```

Error:
```text
Godot Engine v4.1.1.stable.mono.official (c) 2007-present Juan Linietsky, Ariel Manzur & Godot Contributors.
--- Debug adapter server started ---
--- GDScript language server started ---
  core/extension/gdextension.cpp:601 - GDExtension's compatibility_minimum (4.0.0) must be at least 4.1.0: res://addons/godot-git-plugin/git_plugin.gdextension
  Failed loading resource: res://addons/godot-git-plugin/git_plugin.gdextension. Make sure resources have been imported by opening the project in the editor at least once.
  editor/plugins/asset_library_editor_plugin.cpp:858 - Error getting image file from URL: https://i.imgur.com/957uefl.png
```

Switched to 
```ini
compatibility_minimum = 4.1.0
```

Error:
```text
  core/extension/gdextension.cpp:628 - No GDExtension library found for current OS and architecture (windows.x86_64) in configuration file: res://addons/godot-git-plugin/git_plugin.gdextension
  ```

Caused by [parsing as number](https://github.com/godotengine/godot-docs/issues/7864).

Switched to
```ini
compatibility_minimum = "4.1.0"
```

Godot crashes (immediately if running or without showing GUI when started again)!

So still stuck.  Can't see how this would differ if I try building from source.
This is such a pain since (a) it used to work fine and (b) I want to use for Ludum Dare this weekend!

Any ideas?

**Comment by Calinou** [comment]
Thanks for the report! Consolidating in https://github.com/godotengine/godot-git-plugin/issues/196.
