### ISSUE TITLE
Unrecognized by godot.

### ISSUE THREAD

**Issue by AllenKll** [godotengine/godot-git-plugin#29]
I did as the wiki explained ... or at least tried.  The wiki installation says to unzip with content of the zip file to the godot root project folder.

I assume this is meant to be where the godot binary is located?  There is no mention of "root project folder" anywhere in the godot documentation.

After quitting my project to the godot project manager and re-opening my project, I tried to set up source control and received error: "No VCS addons are available."  

Details:
windows 10, 
godot 3.2.1 Stable.
Plugin version 1.2

**Comment by AllenKll** [comment]
After dickering around for a while.  I eventually moved the contents of the zip file to inside my project folder next to my "project.godot" file. This seems to work, but I'm sure this can't be the correct solution, as it would only work for this single project and not for all godot projects.

**Comment by IronicallySerious** [comment]
That is a limitation imposed by Godot's plugin system or at least how Godot handles plugins. It is expected to be quite complex to implement global plugins that can be shared amongst multiple projects. You can read up on the state of global plugins in Godot here: https://github.com/godotengine/godot/pull/35432

About your misfortune with the wiki not telling you exactly where to extract the plugin, I will add a small clarification in the wiki so that this doesn't happen again :)
