### ISSUE TITLE
Plugin UI and Branching

### ISSUE THREAD

**Issue by venomdev** [godotengine/godot-git-plugin#33]
Is it possible to add branching or is this a limit of the Godot git API?

How much are you able to control the git UI in Godot?

**Comment by IronicallySerious** [comment]
@venomdev This plugin was built parallelly with a VCS plugin for Godot. There are bits of code in both this repo and the Godot Engine editor that help run the VCS integration. For more information on what runs this plugin, head [here](https://docs.godotengine.org/en/stable/classes/class_editorvcsinterface.html#editorvcsinterface)

To answer your question, this plugin is theoretically not limited by the Godot API because we are allowed to make changes in Godot for the sake of bettering this plugin (at least for now when we are only ones making VCS plugins). 

Yes, it is possible to add branching with minor changes and actually one of the GSoC projects for Godot is involving an improvement to the VCS UI in Godot so you can look forward to that for now.

**Comment by ChronicallySerious** [comment]
Branching is now merged in master.
