### ISSUE TITLE
Pre-check on .git folder existence

### ISSUE THREAD

**Issue by chucklepie** [godotengine/godot-git-plugin#40]
Hello,
If a project already has a git repository there should be no need to Initialise it again. Perhaps check for .git existence (or maybe better a git rev-parse to return if it's valid) on startup then the button can be removed/updated accordingly.

To save on another issue, would be nice to have a push option, even if a first version meant you had to add your own remote and create the upstream branch prior so the plugin simply ran a 'push' and presumed it was configured ok...

**Comment by IronicallySerious** [comment]
We are in discussion on this feature and it is indeed a feature we'd like to have. Also this is something to fix within the Godot editor and rather than this plugin but that's okay. 

We will be keeping this issue open for now so that this can be tracked easily. 

As for the push operation, we have that already in the works as a part of a project under GSoC 2020 :)

**Comment by twaritwaikar** [comment]
Godot 3.5+ and Godot 4.0+ should solve this problem. There is now an autoload feature where you can set the editor to autoload the VCS plugin used the last time the VCS features were active.
