### ISSUE TITLE
When staging directories, stage the directory instead of directory/

### ISSUE THREAD

**Issue by HaSa1002** [godotengine/godot-git-plugin#6]
When staging directories, stage the directory instead of directory/. Otherwise the directory wouldn't be staged.

**Comment by IronicallySerious** [comment]
I remember that Git does not track directories per se. It records the file names of the staged files and uses the directory name as a part of the file name instead.
When we run `git add directory/` it essentially queries every file in that directory and adds them to the index tree, instead of recording an entire directory in the index.
Please let me know if I have been mistaken in understanding your issue

**Comment by HaSa1002** [comment]
What I meant was, when I do the following:
```
git add directory/
```
I get an error and nothing is staged.
When I do
```
git add directory
```
The staging worked.

**Comment by Calinou** [comment]
This could be a Windows-specific issue. On Linux, the following works fine:

```
# While in a Git repository
mkdir hello
touch hello/hi
git add hello/
```

**Comment by IronicallySerious** [comment]
I am not sure where you are running these commands, because this plugin is supposed to be used from the Godot Engine Editor UI and doesn't allow any direct input to the CLI functionalities as of now. Running Git commands in a separate terminal is something we cannot control from Godot's VCS Integrations's jurisdiction, I presume.

**Comment by HaSa1002** [comment]
I justed wanted to state that staging i.e. assets/ does not work in the editor. and to test I used the the cli git from my console.

**Comment by IronicallySerious** [comment]
I see, could you send a few reproduction steps? I will see to it.

**Comment by HaSa1002** [comment]
![grafik](https://user-images.githubusercontent.com/14185889/66473504-ab7f9980-ea8f-11e9-994b-ab4549cd8306.png)
I staged the selected files:
![grafik](https://user-images.githubusercontent.com/14185889/66473550-c2be8700-ea8f-11e9-9810-98d41839b93c.png)

Commited the files
![grafik](https://user-images.githubusercontent.com/14185889/66473607-df5abf00-ea8f-11e9-899c-788d4e0dc9ca.png)

Now, in the terminal:
Well that is weired now `git add assets/` worked
![grafik](https://user-images.githubusercontent.com/14185889/66473818-555f2600-ea90-11e9-9fd5-31dd6ccb923d.png)

Again in the Editor, after a click on the refresh, the folder is gone:
![grafik](https://user-images.githubusercontent.com/14185889/66473885-74f64e80-ea90-11e9-9e48-036c164db4bc.png)

**Comment by HaSa1002** [comment]
But nevertheless staging the whole directory didn't worked.

**Comment by IronicallySerious** [comment]
Thank you

**Comment by IronicallySerious** [comment]
@HaSa1002 You may use the new release now instead :)

**Comment by HaSa1002** [comment]
Thank you
