### ISSUE TITLE
Ability to push?

### ISSUE THREAD

**Issue by maciek134** [godotengine/godot-git-plugin#7]
Hi, loving the plugin so far! It's really convenient, but I don't see the ability to push changes to remote? Is it planned / in the works maybe? I'd be happy to help.

**Comment by IronicallySerious** [comment]
The ability to push to remote is quite required, seeing the recent requests. We should have a discussion on this with the devs for the best to do this. You can join in on the freenode channel at #godotengine-devel too.

**Comment by tghgg** [comment]
Would love the ability to push to remotes. I'm working on a game right now and would love to have the non-techie artist I'm working with to be able to use Git intuitively in the engine, and get my latest changes to the game through GitHub instead of waiting for me to send a game build once a week.

**Comment by IronicallySerious** [comment]
The push/pull/fetch feature has been developed for the next release :)

If we are able to merge it in time, it will work with Godot's 3.2.x and 4.0
release.

All thanks to our GSoC student project this year.

**Comment by Serenitor** [comment]
> EDIT: Now it can only be done for Godot 4.0

out of curiosity, can I ask for a brief explanation as to why that is the case?

it is perplexing to me why there cannot be a button that simply issues a `git push` while buttons to handle much more complex git commands are fine. and what has any of this to do with Godot's version?

**Comment by Calinou** [comment]
> it is perplexing to me why there cannot be a button that simply issues a git push while buttons to handle much more complex git commands are fine. and what has any of this to do with Godot's version?

Unlike committing, pushing has to handle HTTPS and/or SSH authentication. These typically require going through prompts or setting up a SSH agent. Unless the user has already set up a session-wide SSH agent, pushing won't work out of the box.

**Comment by ChronicallySerious** [comment]
What @Calinou has said above is true, however libgit2 (our Git operations library which we use at the backend) should likely have some arrangements to get pass those issues. 

The more accurate reason imo is that every change to the `EditorVCSInterface` can only be shipped with a new Godot release, which means if there are some changes needed in the API to implement some feature (which it probably is considering how barebones the API is), it needs to wait for the next engine release to get implemented in the plugin present here. 

As for why we can't just add a push button, actually we can add it and it has also already been added in the improvements planned for v2 of this plugin but we had the issue of which engine version to target with it. 

We had the option of either:

1. Add the pull/push/fetch and more features to Godot 3.2 and update the plugin with the implementation
2. Or, save those features for Godot 4.0

We were originally on the side of saving it for Godot 4.0 directly because adding it to the recent/upcoming releases like 3.2.x and 3.3 would be too big of a change and would potentially add lots of bugs. Plus, GDNative was going to change in 4.0 so since it was envisioned that adding the same features to two engine versions together with potentially very different GDNative environments would add development effort. 

However, what I said above was the case till janglee mentioned if working on a 3.4 port of the new features would be desirable for 3.4 to which devs aggreed upon over Rocket.Chat so we might see new features dropping when 3.4 releases :D

Currently 3.3 is in rc stage so adding it to 3.3 made little sense in the first place, according to other core developers as well.

**Comment by ChronicallySerious** [comment]
The Godot 3.5 beta1 is now live. And along with it, we released a v2.0.0 of this plugin which should fix this issue. Push/pull/fetch should work out of the box now.
