### ISSUE TITLE
Plugin deactivated after closing and reopening project on Mac OSX

### ISSUE THREAD

**Issue by jcdescy** [godotengine/godot-git-plugin#74]
As the title says: I can install and activate the plugin in my Godot project. However, whenever I close my project and open it again, the plugin seems to be deactivated. The commit tab is gone and I can only set up version control again. Godot 3.3.2, Git Plugin 1.2.1, Mac OS X Catalina 10.15.7

**Comment by ChronicallySerious** [comment]
The plugin state in terms of being initialized in a project is currently not getting tracked in Godot 3.3.2. However, this problem is not solvable in this plugin and instead, it needs to be reported to the main Godot issue tracker.

https://github.com/godotengine/godot/pull/39255 adds this functionality, so you can use it to track this feature.

**Comment by generrosity** [comment]
Win10 - just gotten via AssetLib, working, just hitting 'reinitialize' after starting Godot. Is that the right workaround at the moment ?

Tracing through your PRs, is this particular bug related to https://github.com/godotengine/godot/pull/53900 or being resolved somewhere else?

Thanks :)

**Comment by ChronicallySerious** [comment]
@generrosity Yes, that would be the workaround for now. It's more like an unimplemented feature rather than a workaround at this point.

And yes, that's the correct PR

**Comment by ChronicallySerious** [comment]
This is now fixed in Godot 3.5 beta1.
