### ISSUE TITLE
Can't install from AssetLib: files failed extraction from package

### ISSUE THREAD

**Issue by danielittlewood0** [godotengine/godot-git-plugin#92]
## Environment

Reproduced on version 3.2.3 and 3.4.0.

## Steps to reproduce

* Open a new project
* Click into Asset lib and search for "Godot Git Plugin"
* Download and install

Extraction gets to 100%, and I get an error message:

```
The following files failed extraction from package:
res://godot-git-plugin/thirdparty/libgit2/tests/resources/status/
```

Any idea what might be causing this?

**Comment by ChronicallySerious** [comment]
@danielittlewood0 Currently, the installation requires you to only download the `demo/addons/` folder. You should be seeing a menu to select the file directories you want to download through the editor.

**Comment by Calinou** [comment]
> @danielittlewood0 Currently, the installation requires you to only download the `demo/addons/` folder. You should be seeing a menu to select the file directories you want to download through the editor.

Should we add a `.gitattributes` file to exclude unnecessary files from the ZIP archive download? See https://github.com/Calinou/godot-addon-template/blob/master/.gitattributes for an example.

**Comment by ChronicallySerious** [comment]
Yeah, @Calinou I have trying to do that but what I also wanted to achieve with that is putting the `addons/` in the root of the repository. So far I haven't been able to do that because I also intend to have a demo project running.

It's mostly a plugin developer thing. If we put `addons/` at the root and we also put a `project.godot` at the root (to test the plugin easily), then the .git repository that is detected in the plugin is the .git repository of this particular repository, which would make it very cumbersome to actually test anything properly without needing to revert all the testing commits we'd make from the editor.

**Comment by ChronicallySerious** [comment]
I would love any ways to fix that, once that is figured out, then pulling out addons/ in the repo root directory is a no-brainer

**Comment by ChronicallySerious** [comment]
This was fixed by @Calinou helping me add a custom download provider in Asset library! Now users just need to install the plugin through the editor, and the default settings for download paths will *just* work :tada:
